image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - server test
  - client test
  - build client
  - build server
  - deploy

server test:
  stage: server test
  image: node:14
  script:
    - echo "Starting server tests"
    - pwd
    - npm install
    - CI=true npm test
    - echo "Test executed successfully!"

client test:
  stage: client test
  image: node:14
  script:
    - echo "Starting client tests"
    - pwd
    - cd client
    - npm install
    - CI=true npm test
    - echo "Test executed successfully!"

build client:
  stage: build client
  image: node:14
  script:
    - echo "Starting build"
    - pwd
    - npm install
    - npm build
    - echo "Build successful!"


build server:
  only:
    - tags
    - staging
  stage: deploy
  script:
    - cd ..
    - docker build -t marmiss/frontend:${CI_COMMIT_TAG}
    - docker push marmiss/frontend:${CI_COMMIT_TAG}
